alias ls='ls --color=auto --human-readable'
alias sl='ls'
alias l='ls -lah --color=auto'
alias vi='vim'
alias ga='git add'
alias gaa='git add .'
alias gc='git commit'
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'
alias ln='ln -v'
alias grep='grep --color=auto'
