alias cp='cp -v'
alias grep='grep --color=auto'
alias l='ls -lah --color=auto'
alias ln='ln -v'
alias ls='ls --color=auto --human-readable'
alias mv='mv -v'
alias naut='nautilus --new-window "$PWD" >/dev/null 2>/dev/null &'
alias poweroff='sudo openrc-shutdown -p now'
alias reboot='sudo openrc-shutdown -r now'
alias rm='rm -v'
alias sl='ls'
