alias cp='cp -v'
alias gaa='git add .'
alias ga='git add'
alias gc='git commit'
alias grep='grep --color=auto'
alias l='ls -lah --color=auto'
alias ln='ln -v'
alias ls='ls --color=auto --human-readable'
alias mv='mv -v'
alias naut='nautilus --new-window "$PWD" >/dev/null 2>/dev/null &'
alias rm='rm -v'
alias sl='ls'
alias vi='vim'
