#!/bin/sh

xsetroot -cursor_name left_ptr

pidof sxhkd || sxhkd &
picom &
/usr/libexec/polkit-gnome-authentication-agent-1 &
dunst &
$HOME/.config/polybar/launch.sh
$HOME/.config/scripts/chpaper.sh &
pidof conky || conky &
pidof mpd || mpd &
#env KEYBASE_AUTOSTART=1 run_keybase &
#ipfs daemon &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a imv state=floating
bspc rule -a scrcpy state=floating
bspc rule -a mpv state=floating
bspc rule -a Virt-manager state=floating
bspc rule -a Arandr state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nvidia-settings state=floating
bspc rule -a jetbrains-studio state=floating
bspc rule -a discord desktop='^10'
bspc rule -a TelegramDesktop desktop='^10'

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
