#!/bin/busybox sh

die() {
	echo -e "Last command said, and I quote, '\e[1;31m$1\e[00m'"
	echo "(Here's a shell in case you know what to do)"
	exec setsid cttyhack /bin/sh
}

borked() {
	echo "Booted into busybox based recovery shell."
	echo "Recover away...!"
	exec setsid cttyhack /bin/sh
}

echo "Beware, Inside there be Dragons!"

# mount /proc, /sys and /dev
mount -t proc none /proc || die "/proc mount failed"
mount -t sysfs none /sys || die "/sys mount failed"
mount -t devtmpfs none /dev || die "/dev mount failed"

for param in $(cat /proc/cmdline); do
	case $param in
		borked)
			borked
		;;
		root=*)
			root="${param#*=}"
		;;
		resume=*)
			resume="${param#*=}"
		;;
	esac
done

# find root and swap partitions
root="$(findfs ${root})"
resume="$(findfs ${resume})"

[ -z "${root}" ] && die "No root partition specified"
[ -z "${resume}" ] && die "No resume partition specified"

printf '%u:%u\n' $(stat -L -c '0x%t 0x%T' ${resume}) > /sys/power/resume || die "trying to resuming failed"

# Mount the real root
mount -t btrfs -o defaults,rw,subvol=/ ${root} /mnt/root || die "unable to mount real root"

# Clean up
umount /proc
umount /sys
umount /dev

# Switch to the real root
exec switch_root /mnt/root /sbin/openrc-init || die "unable to start PID 1"
