#!/bin/busybox sh

die() {
	echo "Oops! You're fucked. Do you happen to have any live USBs around?"
	echo -e "Last command said, and I quote, '\e[1;31m#{$1}\e[00m'"
	echo "(Here's a shell in case you know what to do)"
	exec sh
}

echo "Beware, Inside there be Dragons!"

# mount /proc, /sys and /dev
mount -t proc none /proc || die "/proc mount failed."
mount -t sysfs none /sys || die "/sys mount failed."
mount -t devtmpfs none /dev || die "/dev mount failed."

for PARAM in $(cat /proc/cmdline); do
	case "${PARAM}" in
		root=*)
			root="$(findfs ${PARAM#*=})"
		;;
		resume=*)
			resume="$(findfs ${PARAM#*=})"
		;;
		ro|rw)
			mount_ro_rw="${PARAM}"
		;;
	esac
done

# Open the encrypted partitions
mount -o "${mount_ro_rw}" ${root} /mnt/root || die "mounting /mnt/root failed."

echo "Trying to resume from ${resume}"
printf "%u:%u\n" $(stat -L -c '0x%t 0x%T' ${resume}) > /sys/power/resume || die "cannot resume."


# Clean up
umount /proc
umount /sys
umount /dev

# Switch root
exec switch_root /mnt/root /sbin/openrc-init || die "switch_root failed. You were this close to success."
