#!/bin/bash

DIR="$HOME/Pictures/Wallpapers"
PAPER_LIST="$HOME/.cache/papers.list"
if [ -f "$PAPER_LIST" ]; then
	rm "$PAPER_LIST"
fi
cd "$DIR"

for FILE in $(ls "$DIR"); do
	echo "file://$DIR/$FILE" >> "$PAPER_LIST"
done

RANDOM_PAPER=$(shuf -n 1 "$PAPER_LIST")
RANDOM_LOCK=$(shuf -n 1 "$PAPER_LIST")

gsettings set org.gnome.desktop.background picture-uri "$RANDOM_PAPER"
gsettings set org.gnome.desktop.background primary-color "#000000"
gsettings set org.gnome.desktop.background secondary-color "#000000"

gsettings set org.gnome.desktop.screensaver picture-uri "$RANDOM_LOCK"
gsettings set org.gnome.desktop.screensaver primary-color "#000000"
gsettings set org.gnome.desktop.screensaver secondary-color "#000000"

echo "Wallpaper: $RANDOM_PAPER"
echo "Lockscreen: $RANDOM_LOCK"
