#!/bin/bash

DIR="$HOME/Pictures/Wallpapers"

RANDOM_PAPER="file://$(/bin/ls $DIR/*/* | /usr/bin/shuf -n 1)"
RANDOM_LOCK="file://$(/bin/ls $DIR/*/* | /usr/bin/shuf -n 1)"

gsettings set org.gnome.desktop.background picture-uri "$RANDOM_PAPER"
gsettings set org.gnome.desktop.background primary-color "#000000"
gsettings set org.gnome.desktop.background secondary-color "#000000"

gsettings set org.gnome.desktop.screensaver picture-uri "$RANDOM_LOCK"
gsettings set org.gnome.desktop.screensaver primary-color "#000000"
gsettings set org.gnome.desktop.screensaver secondary-color "#000000"

echo "Wallpaper: $RANDOM_PAPER"
echo "Lockscreen: $RANDOM_LOCK"
